algoritmo "Exercicio 2"

var

Valor_Total:Real
Qtde_Parcelas:Inteiro

inicio

escreval ("Digite o Valor total da sua compra: ")
leia (Valor_Total)

escreval ("Quantas vezes deseja parcelar: ")
leia (Qtde_Parcelas)

Limpatela

escreval ("Sua compra foi de " , Valor_Total:2:2 , " reais")

escreval ("Você optou por parcelar em" , Qtde_Parcelas , " vezes")

escreval ("Sua parcela mensal é de:" , Valor_Total/Qtde_Parcelas:2:2 , " reais")


fimalgoritmo

