algoritmo "Exercicio 2"


var

valorTotal:Real
macasCompradas:Inteiro


inicio
escreval("Quantas maças foram compradas?")
leia (macasCompradas)

se (macasCompradas>=12)entao
   valorTotal<-macasCompradas*1.0
   escreval("Custo total das maças: " , valortotal:2:2 , " Reais")
senao
   valorTotal<-macasCompradas*1.30
   escreval ("Custo total das maças: " , valorTotal:2:2 , " Reais")
fimse

fimalgoritmo
